/*
 * Copyright (C) 2011 Nipuna Gunathilake.
 * All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package edu.usf.cutr.gtfsrtvalidator.lib.validation.interfaces;

import com.google.transit.realtime.GtfsRealtime;
import edu.usf.cutr.gtfsrtvalidator.lib.model.helper.ErrorListHelperModel;
import edu.usf.cutr.gtfsrtvalidator.lib.validation.GtfsMetadata;
import org.onebusaway.gtfs.services.GtfsMutableDao;

import java.util.List;

/**
 * Interface used for all rules that produce error or warning messages
 */
public interface FeedEntityValidator {
    /**
     * Validates a particular rule implemented by this interface
     *
     * @param currentTimeMillis the current system time, in milliseconds
     * @param gtfsData    GTFS schedule data
     * @param gtfsMetadata Data structures that contain processed information about the GTFS data
     * @param feedMessage Current GTFS-rt data that was most recently captured (should NOT be equal to previousFeedMessage)
     * @param previousFeedMessage Previous GTFS-rt data from the previous iteration of the feed (should NOT be the same as feedMessage)
     * @param combinedFeedMessage A GTFS-rt message that includes entities from all GTFS-rt feeds being monitored simultaneously for the same GTFS dataset.  If only one GTFS-rt feed is being monitored for the GTFS dataset, then this is null.
     * @return a list of errors and warnings that was generated by the implementing rule
     */
    List<ErrorListHelperModel> validate(long currentTimeMillis, GtfsMutableDao gtfsData, GtfsMetadata gtfsMetadata, GtfsRealtime.FeedMessage feedMessage, GtfsRealtime.FeedMessage previousFeedMessage, GtfsRealtime.FeedMessage combinedFeedMessage);
}
